version: '3'
 
services:
  db:
    image: mariadb
    container_name: '${APP_NAME}-db'
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
      - wpsite
  wp:
    build:
      context: ./docker
    container_name: '${APP_NAME}-app'
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - wpsite
    environment:
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      WP_DEBUG: 1
networks:
  wpsite: 
volumes:
  db_data: # store database into a volume so that we can pause the containers